---
# Centralized globals for VMware config drift playbooks

# vCenter (or ESXi) API connection
vcenter_hostname: "vcenter.home.virtualelephant.com"
vcenter_username: "administrator@vsphere.local"
vcenter_password: "{{ vault_vcenter_password }}"   # put in Ansible Vault
vcenter_port: 443
vcenter_validate_certs: false

# Target ESXi hosts to audit (by inventory_hostname or explicit hostnames)
esxi_hosts:
  - "esxi01.home.virtualelephant.com"
  - "esxi02.home.virtualelephant.com"
  - "esxi03.home.virtualelephant.com"
  - "esxi04.home.virtualelephant.com"

# DNS
dns_nameservers:
  - 10.1.10.11
  - 10.1.10.12
dns_search_domains:
  - home.virtualelephant.com
  - cilium.virtualelephant.com

# NTP (chrony)
ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org

# Either define a composed list:
esxi_syslog_targets:
  - "udp://log.home.virtualelephant.com:514"
  # - "tcp://log.home.virtualelephant.com:514"

# Or define single-endpoint pieces (playbook composes these if the list is absent):
syslog_protocol: udp
syslog_host: log.home.virtualelephant.com
syslog_port: 514

# Desired syslog forwarding targets (max 3 per VCSA)
# protocol: udp|tcp|tls|relp
# port: typical rsyslog ports 514/6514/etc.
vcsa_syslog_targets:
  - host: "rsyslog01.example.net"
    protocol: "tcp"
    port: 514

# === ESXi Scratch & Core Dump (Global Defaults) ==============================

# Persistent scratch configuration. If 'path' is empty, the playbook will
# compose a path using the datastore name: /vmfs/volumes/<datastore>/<dir>/<esxi_name>
esxi_scratch:
  datastore: "vsanDatastore"     # e.g., "vsanDatastore" or "datastore1"
  dir: "scratch"                 # subdirectory under the datastore
  path: ""                       # optional FULL path; if set, overrides datastore/dir
  allowlist: []                  # hosts to SKIP scratch enforcement (break-glass)
                                 # e.g., ["esxi01.home.virtualelephant.com"]

# Core dump configuration (choose one mode globally; override per host/cluster if needed).
# mode: network | file | disabled
esxi_coredump:
  mode: "network"

  # Skip core dump enforcement for specific hosts (break-glass).
  allowlist: []

  # Network core dump collector settings (used when mode == "network")
  network:
    vmk: "vmk1"                  # VMkernel interface to source dumps
    host: "10.1.100.50"          # collector IP/FQDN
    port: 6500                   # collector port (default 6500)

  # File-based core dump settings (used when mode == "file")
  # If you want the playbook to build this automatically from the scratch datastore,
  # leave 'path' empty and set 'path_template' instead.
  file:
    path: ""                     # optional FULL path, e.g., /vmfs/volumes/vsanDatastore/coredump/<host>/coredump
    path_template: "/vmfs/volumes/{{ esxi_scratch.datastore }}/coredump/{{ esxi_name }}/coredump"
