---
# Centralized globals for VMware config drift playbooks

# vCenter (or ESXi) API connection
vcenter_hostname: "vcenter.home.virtualelephant.com"
vcenter_username: "administrator@vsphere.local"
vcenter_password: "{{ vault_vcenter_password }}"   # put in Ansible Vault
vcenter_port: 443
vcenter_validate_certs: false

# Target ESXi hosts to audit (by inventory_hostname or explicit hostnames)
esxi_hosts:
  - "esxi01.home.virtualelephant.com"
  - "esxi02.home.virtualelephant.com"
  - "esxi03.home.virtualelephant.com"
  - "esxi04.home.virtualelephant.com"

# DNS
dns_nameservers:
  - 10.1.10.11
  - 10.1.10.12
dns_search_domains:
  - home.virtualelephant.com
  - cilium.virtualelephant.com

# NTP (chrony)
ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
